### PR TITLE
Re-assign ModSpec identifiers according to OGC instructions

### LINKED ISSUE #8: Re-assign ModSpec identifiers according to OGC instructions
This is a mapping provided by @ghobona:

[GeoPose.xlsx](https://github.com/metanorma/ogc-GeoPose/files/9714309/GeoPose.xlsx)

@metanorma/editors could you please help rename the identifiers as provided by this Excel sheet? Thanks!

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
Fixes https://github.com/metanorma/ogc-GeoPose/issues/8

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
Remaining correspondence issues:
````
Requirements: (XML Line 001607): Requirement /req/frame_specification/authority has no corresponding Conformance test
Requirements: (XML Line 001618): Requirement /req/frame_specification/id has no corresponding Conformance test
Requirements: (XML Line 001629): Requirement /req/frame_specification/parameters has no corresponding Conformance test
Requirements: (XML Line 001828): Requirement /req/graph/sdu-graph-transform-index has no corresponding Conformance test
Requirements: (XML Line 004371): Conformance test /conf/graph/sdu-graph-index has no corresponding Requirement
Requirements: (XML Line 004510): Conformance test /conf/chain/sdu-chain-index has no corresponding Requirement
Requirements: (XML Line 004995): Conformance class /conf/basic-ypr-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005039): Conformance class /conf/basic-quaternion-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005082): Conformance class /conf/basic-quaternion-encoding-json-strict has no corresponding Requirement class
Requirements: (XML Line 005124): Conformance class /conf/advanced-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005166): Conformance class /conf/chain-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005208): Conformance class /conf/graph-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005250): Conformance class /conf/series-regular-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005292): Conformance class /conf/series-irregular-encoding-json has no corresponding Requirement class
Requirements: (XML Line 005334): Conformance class /conf/stream-encoding-json has no corresponding Requirement class
````

These are due to authentic missing requirements in the document, as they are pointed in [GeoPose_2.xlsx](https://github.com/metanorma/ogc-GeoPose/files/9735755/GeoPose_2.xlsx).

**Comment by manuelfuenmayor** [comment]
@ronaldtse, please take a look at https://github.com/metanorma/ogc-GeoPose/pull/9/commits/093c4d8b37b8a3820ff788775727b5a73ff1ddad.
Not sure if what I did was correct.

Basically, I added three new conformance tests:
`/req/stream-encoding-json/header`,
`/req/stream-encoding-json/element` and
`/req/stream/report/encoding/json`.

according to OGC instructions.
But maybe that was a job for the OGC Editor?

**Comment by ronaldtse** [comment]
@manuelfuenmayor I think:
`/req/stream/report/encoding/json`
should have been:
`/req/stream-encoding-json`

**Comment by ronaldtse** [comment]
I have redone all the ModSpec instances and reimplemented them using the YAML approach. In addition, I rewrote quite a number of them that did not make sense (inherited from the original document).

All items now validate, except for this particular one:

```
Requirements: (XML Line 001714): Requirement /req/basic-quaternion/quaternion has no corresponding Conformance test
Requirements: (XML Line 004376): Conformance test /conf/basic-quaternion/quaternion has no corresponding Requirement
```

However, they are clearly matching in the YAML files. This seems like a bug for @opoudjis ?

**Comment by ronaldtse** [comment]
Requirement:
Screen Shot 2022-10-10 at 3 43 51 PM

Conformance test:
image

**Comment by ronaldtse** [comment]
> However, they are clearly matching in the YAML files. This seems like a bug for @opoudjis ?

Sorry, thanks to @manuelfuenmayor for finding the problem: when the description has more than one paragraph, it fails because of the liquid template. I've fixed it in 1358bc3.

**Pull request merged**
